# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: dir ${{ github.workspace }}
      - uses: microsoft/variable-substitution@v1 
        with:
          files: ${{ github.workspace }}\web.config
        env:
          demoVar: "fixed!"
          demoVar2: "fixed!"
      - run: get-content ${{ github.workspace }}\web.config
